version: "3.1"

services:
    webserver:
      image: nginx:stable-alpine
      container_name: store-webserver
      working_dir: /var/www/app
      ports:
        - "${APP_PORT}:80"
      volumes:
        - .:/var/www/app
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
          - app-network

    app:
      build: ./docker/php-fpm
      container_name: store-app
      working_dir: /var/www/app
      volumes:
        - .:/var/www/app
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      networks:
          - app-network

    mysql:
      image: mysql:5.7.22
      container_name: store-mysql
      working_dir: /var/www/app
      volumes:
        - .mysqldata:/var/lib/mysql
        - ./docker/mysql:/etc/mysql/conf.d
      ports:
        - "${MYSQL_PORT}:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=hrtools
        - MYSQL_USER=user
        - MYSQL_PASSWORD=secret
      networks:
        - app-network

    beanstalkd:
      image: schickling/beanstalkd
      container_name: store-beanstalkd

    redis:
        image: redis:5
        container_name: store-redis

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
        restart: always
        ports:
            - 8081:80
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
